### ISSUE TITLE
Remove lodash (currently used for throttling)

### ISSUE THREAD

**Issue by tonygentilcore** [gnoff/react-everscroll#2]
Would be awesome :)

**Comment by gnoff** [comment]
Hi @tonygentilcore would you suggest not throttling or just implementing a local throttling function?

either way, I'm inclined actually to mark this project as abandoned mostly because

https://github.com/bvaughn/react-virtualized

is so much better and I haven't been using it myself for a long while. Check out react-virtualized, you'll probably get every feature I have here with much better performance and support.

Thanks,
Josh
